# Repository settings set via https://github.com/probot/settings

repository:
  has_issues: true
  has_wiki: false
  has_projects: false
  has_downloads: false

labels:
  - name: help-wanted
    color: "0e8a16"
  - name: problem
    color: "d93f0b"
  - name: bug
    color: "b60205"
  - name: feature
    color: "1d76db"
  - name: another-label
    color: "5319e7"

